CRITICAL - 2021-12-07 02:14:26 --> Undefined variable $login
#0 C:\xampp\htdocs\suratci\app\Views\suratin.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 11)
#1 C:\xampp\htdocs\suratci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\suratci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\suratci\system\Common.php(1097): CodeIgniter\View\View->render('suratin', Array, true)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(41): view('suratin')
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->hapus('3')
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 02:16:17 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\suratci\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\suratci\system\Common.php(840): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(41): redirect('/suratin')
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->hapus('1')
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-07 19:00:39 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\suratci\app\Views\suratin.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\suratci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\suratci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\suratci\system\Common.php(1097): CodeIgniter\View\View->render('suratin', Array, true)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(22): view('suratin', Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 19:02:56 --> Object of class App\Models\SuratIn could not be converted to string
#0 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#1 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-07 19:06:13 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\suratci\app\Views\suratin.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\suratci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\suratci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\suratci\system\Common.php(1097): CodeIgniter\View\View->render('suratin', Array, true)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(23): view('suratin', Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 19:06:46 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\suratci\app\Views\suratin.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\suratci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\suratci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\suratci\system\Common.php(1097): CodeIgniter\View\View->render('suratin', Array, true)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(23): view('suratin', Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 19:06:47 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\suratci\app\Views\suratin.php(30): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\xampp\\htdocs...', 30)
#1 C:\xampp\htdocs\suratci\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\suratci\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\suratci\system\Common.php(1097): CodeIgniter\View\View->render('suratin', Array, true)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(23): view('suratin', Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-12-07 19:07:58 --> Unknown column 'title' in 'order clause'
CRITICAL - 2021-12-07 19:07:58 --> Unknown column 'title' in 'order clause'
#0 C:\xampp\htdocs\suratci\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\suratci\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\suratci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\suratci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(15): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#8 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#9 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-07 19:07:59 --> Unknown column 'title' in 'order clause'
CRITICAL - 2021-12-07 19:07:59 --> Unknown column 'title' in 'order clause'
#0 C:\xampp\htdocs\suratci\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\suratci\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\suratci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\suratci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(15): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#8 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#9 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-07 19:10:35 --> Undefined variable $query1
#0 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-07 19:10:36 --> Undefined variable $query1
#0 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 23)
#1 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-07 19:11:10 --> Undefined variable $db
#0 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16)
#1 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-12-07 19:18:56 --> Unknown column 'title' in 'order clause'
CRITICAL - 2021-12-07 19:18:56 --> Unknown column 'title' in 'order clause'
#0 C:\xampp\htdocs\suratci\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\suratci\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\suratci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\suratci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(24): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#8 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#9 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-12-07 19:18:57 --> Unknown column 'title' in 'order clause'
CRITICAL - 2021-12-07 19:18:57 --> Unknown column 'title' in 'order clause'
#0 C:\xampp\htdocs\suratci\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\suratci\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\suratci\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\suratci\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\suratci\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(24): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->index()
#8 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#9 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-07 20:55:37 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\suratci\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(63): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 20:58:49 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-07 21:00:39 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\suratci\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:00:42 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\suratci\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:02:12 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\suratci\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:02:32 --> Allowed fields must be specified for model: App\Models\SuratIn
#0 C:\xampp\htdocs\suratci\system\BaseModel.php(1138): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Sura...')
#1 C:\xampp\htdocs\suratci\system\BaseModel.php(713): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\suratci\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\Model->insert(Array)
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-07 21:34:14 --> finfo_file(C:\xampp\tmp\php42FE.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #151, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:38:55 --> finfo_file(C:\xampp\tmp\php8B7F.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #151, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:39:38 --> finfo_file(C:\xampp\tmp\php3637.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #151, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:41:55 --> finfo_file(C:\xampp\tmp\php4C85.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #151, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(65): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:51:32 --> finfo_file(C:\xampp\tmp\php1A23.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:52:24 --> finfo_file(C:\xampp\tmp\phpE709.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:52:36 --> finfo_file(C:\xampp\tmp\php136A.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:52:40 --> finfo_file(C:\xampp\tmp\php253D.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(68): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 21:52:50 --> Could not move file php4BE1.tmp to ./public/file/ ()
#0 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(149): CodeIgniter\HTTP\Exceptions\HTTPException::forMoveFailed('php4BE1.tmp', './public/file/', '')
#1 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(62): CodeIgniter\HTTP\Files\UploadedFile->move('./public/file/', '/', true)
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-07 21:53:02 --> Could not move file php7A55.tmp to /file/ ()
#0 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(149): CodeIgniter\HTTP\Exceptions\HTTPException::forMoveFailed('php7A55.tmp', '/file/', '')
#1 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(62): CodeIgniter\HTTP\Files\UploadedFile->move('/file/', '/', true)
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-07 21:53:17 --> Could not move file phpB5C8.tmp to /public/file/ ()
#0 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(149): CodeIgniter\HTTP\Exceptions\HTTPException::forMoveFailed('phpB5C8.tmp', '/public/file/', '')
#1 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(62): CodeIgniter\HTTP\Files\UploadedFile->move('/public/file/', '/', true)
#2 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#3 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#4 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-07 22:03:33 --> finfo_file(C:\xampp\tmp\php1B60.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(69): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 22:04:23 --> finfo_file(C:\xampp\tmp\phpDDD7.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #150, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(69): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-07 22:14:10 --> finfo_file(C:\xampp\tmp\phpD4D3.tmp): Failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'finfo_file(C:\\x...', 'C:\\xampp\\htdocs...', 109)
#1 C:\xampp\htdocs\suratci\system\Files\File.php(109): finfo_file(Resource id #148, 'C:\\xampp\\tmp\\ph...')
#2 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(297): CodeIgniter\Files\File->getMimeType()
#3 C:\xampp\htdocs\suratci\system\HTTP\Files\UploadedFile.php(286): CodeIgniter\HTTP\Files\UploadedFile->guessExtension()
#4 C:\xampp\htdocs\suratci\app\Controllers\Surat_In.php(70): CodeIgniter\HTTP\Files\UploadedFile->getExtension()
#5 C:\xampp\htdocs\suratci\system\CodeIgniter.php(824): App\Controllers\Surat_In->simpan()
#6 C:\xampp\htdocs\suratci\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Surat_In))
#7 C:\xampp\htdocs\suratci\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\suratci\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
